//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iprosoft.ELMA.WebApiMail.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ELMA3Entities : DbContext
    {
        public ELMA3Entities()
            : base("name=ELMA3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMailMessageI> EMailMessageI { get; set; }
    
        public virtual ObjectResult<CreateEmailMessageI_Result> CreateEmailMessageI(string name, Nullable<System.DateTime> creationDate, string tema, string soobschenie, Nullable<System.DateTime> dataPolucheniePisjma, string otKogo)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var creationDateParameter = creationDate.HasValue ?
                new ObjectParameter("CreationDate", creationDate) :
                new ObjectParameter("CreationDate", typeof(System.DateTime));
    
            var temaParameter = tema != null ?
                new ObjectParameter("Tema", tema) :
                new ObjectParameter("Tema", typeof(string));
    
            var soobschenieParameter = soobschenie != null ?
                new ObjectParameter("Soobschenie", soobschenie) :
                new ObjectParameter("Soobschenie", typeof(string));
    
            var dataPolucheniePisjmaParameter = dataPolucheniePisjma.HasValue ?
                new ObjectParameter("DataPolucheniePisjma", dataPolucheniePisjma) :
                new ObjectParameter("DataPolucheniePisjma", typeof(System.DateTime));
    
            var otKogoParameter = otKogo != null ?
                new ObjectParameter("OtKogo", otKogo) :
                new ObjectParameter("OtKogo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreateEmailMessageI_Result>("CreateEmailMessageI", nameParameter, creationDateParameter, temaParameter, soobschenieParameter, dataPolucheniePisjmaParameter, otKogoParameter);
        }
    }
}
